version: '3.3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/mysql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p2309"
      POSTGRES_DB: "postgres"